application: rdfendpoints
version: 0-1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(html|js|css))$
  static_files: static/\1
  upload: static/.*\.(html|js|css)$

- url: /startcrawling
  script: Scrawler.py

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"

builtins:
- remote_api: on

cron:
- description: scrawler
  url: /startcrawling
  schedule: every 12 hours